language: python
python:
  - "2.6"
  - "2.7"
  - "2.8"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  - python greenhouseEI_unittest.py -b
